answers_eng_keys = {}

answers_second_test = {}

answers_third_test = {}

english_excercices_first_test = [
    {'activity': ['деятельность', 'защита', 'упражнение', 'лечение']},
    {'amount': ['сумма', 'разность', 'слон', 'сложение']},
    {'author': ['автор', 'осёл', 'репетитор', 'учитель']},
    {'character': ['характер', 'чувство', 'темп', 'директор']},
    {'dictionary': ['словарь', 'лист', 'дикция', 'развод']},
    {'event': ['событие', 'круассан', 'вариант', 'выбор']},
    {'guess': ['предположение', 'адвокат', 'тема', 'парашют']},
    {'dashboard': ['панель управления', 'панель задач', 'лист дел', 'дартс']},
    {'task manager': ['планировщик задач', 'эндокринолог', 'доска задач', 'лечение']},
    {'sick day': ['больничный', 'рабочий день', 'зарядка', 'каникулы']},
    {'trouble': ['проблема', 'заглушка', 'пробка', 'задача']},
    {'deadline': ['срок сдачи', 'гроб', 'отрезок', 'маршрут']},
    {'reason': ['причина', 'аргумент', 'закат', 'конфликт']},
    {'remark': ['замечание', 'поправка', 'изменение', 'стикер']},
    {'weekend': ['выходной', 'начало недели', 'суббота', 'пятница']},
    {'cartoon': ['мультфильм', 'картон', 'сцена', 'проект']},
    {'movie': ['фильм', 'движение', 'волна', 'жанр музыки']},
    {'circus': ['цирк', 'верблюд', 'акробатика', 'биржа']},
    {'composer': ['композитор', 'компост', 'конструктор', 'инженер']},
    {'dream': ['мечта', 'сон', 'барабан', 'идея']},
    {'daily routine': ['ежедневная рутина', 'скучная рутина', 'план на день', 'затягивающая рутина']},
    {'horror': ['хоррор', 'комедия', 'ужасы', 'триллер']},
    {'laughter': ['смех', 'везунчик', 'клевер', 'фортуна']},
    {'novel': ['роман', 'новость', 'море', 'неологизм']},
    {'story': ['рассказ', 'поговорка', 'история', 'басня']},
    {'access': ['доступ', 'проход', 'выполнение', 'отметка']},
    {'account': ['аккаунт', 'пароль', 'логин', 'вход']},
    {'scenery': ['пейзаж', 'сцена', 'ракурс', 'натюрморт']},
    {'mood': ['настроение', 'заглушение', 'состояние', 'клуб']},
    {'binge': ['гулянка', 'башня', 'баржа', 'мост']},
    {'creative': ['креативный', 'умный', 'жадный', 'мерзкий']},
    {'ambitious': ['амбициозный', 'скупой', 'несмышленный', 'наглый']},
    {'curious': ['любопытный', 'ленивый', 'упертый', 'вспыльчивый']},
    {'cheerful': ['жизнерадостный', 'щедрый', 'наглый', 'унывающий']},
    {'honest': ['честный', 'злой', 'дружелюбный', 'скромный']},
    {'hard-working': ['трудолюбивый', 'заносчивый', 'эгоистичный', 'циничный']},
    {'selfish': ['эгоистичный', 'предприимчивый', 'организованный', 'терпеливый']},
    {'generous': ['щедрый', 'серьезный', 'разговорчивый', 'прогрессивный']},
    {'talkative': ['разговорчивый', 'непредсказуемый', 'мотивированный', 'приятный']},
    {'self-confident': ['самоуверенный', 'самоотверженный', 'угрюмый', 'аскетичный']},
    {'courageous': ['отважный', 'искренний', 'грубый', 'подлый']},
    {'strict': ['строгий', 'чуткий', 'упрямый', 'доверчивый']},
    {'suspicious': ['подозрительный', ' замкнутый', 'вежливый', 'безрассудный']},
    {'optimistic': ['оптимистичный', 'уверенный', 'тактичный', 'раскованный']},
    {'unpredictable': ['непредсказуемый', 'спокойный', 'уравновешенный', 'невозмутимый']},
    {'cruise liner': ['круизный лайнер', 'машина', 'самокат', 'моноколесо']},
    {'vehicle': ['средство передвижения', 'автобус', 'троллейбус', 'трамвай']},
    {'truck': ['грузовик', 'дорога', 'квадроцикл', 'моторная лодка']},
    {'van': ['фургон', 'мотоцикл', 'фура', 'истребитель']},
    {'car': ['машина', 'гироскутер', 'скутер', 'велосипед']},
    {'camper': ['дом на колесах', 'паром', 'междугородний автобус', 'самолет']},
    {'ferry': ['паром', 'деревянная лодка', 'водный мотоцикл', 'круизный лайнер']},
    {'coach': ['междугородний автобус', 'тренер', 'троллейбус', 'моноколесо']},
    {'jet ski': ['водный мотоцикл', 'яхта', 'электрический самокат', 'вертолет']},
    {'helicopter': ['вертолет', 'самолет', 'дом на колесах', 'велосипед']},
    {'train': ['поезд', 'яхта', 'космический корабль', 'микроавтобус']},
    {'parrot': ['попугай', 'лиса', 'писец', 'змея']},
    {'snake': ['змея', 'собака', 'заяц', 'кролик']},
    {'pig': ['свинья', 'овца', 'курица', 'петух']},
    {'spider': ['паук', 'динозавр', 'пингвин', 'слон']},
    {'turtle': ['черепаха', 'тигр', 'сова', 'оса']},
    {'dog': ['собака', 'кот', 'скорпион', 'пчела']},
    {'cat': ['кот', 'жираф', 'лошадь', 'козел', 'ягненок']},
    {'donkey': ['осел', 'корова', 'индейка', 'баран']},
    {'horse': ['лошадь', 'бобр', 'тюлень', 'морской котик']},
    {'beetle': ['жук', 'крокодил', 'комар', 'орел']},
    {'hedgehog': ['ёж', 'сайгак', 'горилла', 'крот']},
    {'city': ['город', 'поселок', 'деревня', 'мегаполис']},
    {'street': ['улица', 'гостиница', 'перекресток', 'торговый центр']},
    {'traffic light': ['светофор', 'кинотеатр', 'больница', 'пешеходный переход']},
    {'crosswalk': ['пешеходный переход', 'подземный переход', 'перекресток', 'мост']},
    {'bus station': ['автобусная остановка', 'порт', 'пожарная станция', 'район']},
    {'bridge': ['мост', 'отель', 'мотель', 'округ']},
    {'police department': ['полицейский участок', 'офис', 'депертамент здравоохранения', 'парламент']},
    {'hospital': ['больница', 'хостел', 'собор', 'округ']},
    {'pedestrian': ['пешеход', 'гражданин', 'педант', 'подземный переход']},
    {'subway': ['метро', 'сендвич', 'автобусная осатновка', 'многоэтажный дом']},
    {'mall': ['торговый центр', 'фуд-корт', 'магазин одежды', 'квартира']},
    {'spring': ['весна', 'закат', 'восход', 'осень']},
    {'winter': ['зима', 'осень', 'лето', 'облако']},
    {'climate': ['климат', 'туча', 'бриз', 'облако']},
    {'frost': ['мороз', 'туман', 'осадки', 'град']},
    {'hoarfrost': ['иней', 'туман', 'облако', 'лягушка']},
    {'hail': ['град', 'иней', 'бог', 'молитва']},
    {'rainbow': ['радуга', 'молитва', 'лук', 'река']},
    {'lightning': ['молния', 'электричество', 'сон', 'пробуждение']},
    {'flood': ['наводнение', 'ноябрь', 'потоп', 'утопленник']},
    {'drizzle': ['мелкий дождь', 'крупный дождь', 'град', 'засуха']},
    {'raindrop': ['дождевая капля', 'град', 'сильный дождь', 'маленький дождь']},
    {'government': ['правительство', 'охрана', 'губернатор', 'руководство']},
    {'right': ['право', 'лево', 'закон', 'конституция']},
    {'power': ['власть', 'полиция', 'суд', 'экран']},
    {'community': ['сообщество', 'компания', 'команада', 'коллектив']},
    {'party': ['партия', 'часть', 'вечеринка', 'посиделки']},
    {'election': ['выборы', 'митинг', 'переворот', 'резиденция']},
    {'authority': ['полномочия', 'авторское право', 'авторство', 'аудитория']},
    {'politics': ['политика', 'депутат', 'президент', 'чиновник']},
    {'institution': ['учреждение', 'институт', 'организация', 'участок']},
    {'vote': ['голос (на выборах)', 'билет', 'надежда', 'зарплата']},
    {'citizen': ['гражданин', 'городской', 'поселок', 'город']},
]

english_excercices_second_test = [
    {'I ___ to go outside yesterday.': ['wanted', 'want', 'will want', 'wants']},
    {'She ___ her mother tommorow.': ['will visit', 'visited', 'visit', 'visits']},
    {'He ___ his old brother every day.': ['visits', 'will visit', 'visited', 'visit']},
    {'They ___ about yesterday news.': ['gossip', 'will gossip', 'gossiped', 'gossips']},
    {'He says that it ___ yesterday.': ['worked', 'work', 'works', 'will work']},
    {'Covid ___ seven million people all over the world.': ['killed', 'will kill', 'kill', 'kills']},
    {'He ___ on his girlfriend birthday after two hours.': ['will go', 'went', 'goes', 'go']},
    {'She ___ this huge, tasty burger.': ['ate', 'eat', 'eats', 'will eat']},
    {'It ___ you a lot of energy.': ['gives', 'give', 'will give', 'gave']},
    {'This car ___ a revolution in industry in next four years.': ['will make', 'make', 'makes', 'made']},
    {'Mike ___ cake on his birthday every year': ['eats', 'eat', 'will eat', 'ate']},
    {'Users of apple smartphones ___ high quality.': ['love', 'loves', 'loved', 'will love']},
    {'Next week it ___ the best party of this year': ['will be', 'was', 'is', 'will it']},
    {'I am really sad about tragedy in our city, that ___ 2 years ago.': ['was', 'were', 'been', 'will be']},
    {'I ___ English twice a week.': ['study', 'studied', 'will study', 'studies']},
    {'Our mother ___ us to be brave in our ideas in my childhood.': ['teached', 'teach', 'will teach', 'teachs']},
    {'I ___ this one only after salad.': ['will eat', 'ate', 'eats', 'eat']},
    {'He ___ pancakes with honey on breakfast every morning.': ['eats', 'eat', 'ate', 'will eat']},
    {'I will buy this car and ___ every day.': ['drive', 'drives', 'will drive', 'drove']},
    {'My dad ___ this home 10 years ago.': ['bought', 'buy', 'will buy', 'was buy']},
    {'She ___ up and ___ to school every day at 7 am.': ['wakes, goes', 'wake, goes', 'woke, go', 'wake, goes']},
    {'In future, people ___ new planets.': ['will explore', 'explore', 'explores', 'explored']},
    {'Peter the Great ___ Saint-Petersburg in 1703.': ['founded', 'found', 'will found', 'find']},
    {'They ___ in the center of their city every month.': ['walk', 'walks', 'go', 'went']},
    {'I ___ go to school tommorow, because I feel me bad.': ['will not', 'need', 'will', 'want']},
    {'Yesterday, I ___ outside with my mother.': ['went', 'was', 'were not', 'go']},
    {'He ___ go to this shop, because he ___ a lot of time to go here.': ['does not, needs', 'always, needed', 'prefer to, wanted', 'wanted, spent']},
    {'She ___ celebrate New Year, because she is sick.': ['will not', 'will', 'was', 'is']},
    {'His father ___ this travel.': ['forbidden', 'will forbidden', 'cancel', 'was cancel']},
    {'They ___ to go here, because there are a lot of insects.': ['did not want', 'wanted', 'wants', 'want']},
]


english_excercices_third_test = [
    {'We ___ do our homework.': ['must', 'have to', 'do not have to', 'should']},
    {'We ___ be late at school.': ['must not', 'do not have to', 'should not', 'must']},
    {'We ___ be quiet at the lessons.': ['must', 'should', 'have to', 'do not have to']},
    {'You ___ take your rubbish.': ['must', 'have to', 'should', 'do not have to']},
    {'Students ___ run in classes.': ['must not', 'do not have to', 'should not', 'must']},
    {'You ___ feed animals in our zoo!': ['must not', 'must', 'should', 'have to']},
    {'Your mum ___ wear sun hat when it is hot outside.': ['must', 'has to', 'goes', 'go']},
    {'You ___ be kind to others.': ['must', 'should', 'have to', 'should not']},
    {'You ___ be polite with your teachers and parents.': ['must', 'should', 'do not have to', 'have to']},
    {'We ___ speak loudly at the library.': ['must not', 'should not', 'do not have to', 'must']},
    {'You ___ see the new film! It is great!': ['should', 'must', 'have to', 'should not']},
    {'You ___ smoke! It is very bad habit.': ['should not', 'should', 'must not', 'do not have to']},
    {'Your temperature is high. You ___ call to a doctor.': ['should', 'must', 'have to', 'do not have to']},
    {'Sally ___ with her parents.': ['should not', 'do not have to', 'have to', 'should']},
    {'It is so hot outside! You ___ wear a t-shirt.': ['should', 'have to', 'must not', 'should not']},
    {'You ___ eat here. It is a museum.': ['should not', 'do not have to', 'must', 'should']},
    {'Tanya ___ visit her grandparents more often.': ['should', 'ate', 'eats', 'eat']},
    {'You ___ talk to this rude man, it is bad idea.': ['should not', 'should', 'ate', 'have to']},
    {'Mike ___ take care of your cat.': ['should', 'should not', 'have to', 'must']},
    {'We ___ help people, who need our help.': ['should', 'do not have to', 'must', 'must not']},
    {'She ___ wake up and go to school every day at 7 am.': ['has to', 'have to', 'should', 'must']},
    {'She does not have to write the test tommorow.': ['does not have to', 'should not', 'must not', 'have to']},
    {'My parents ___ go to supermarket tommorow.': ['have to', 'has to', 'must', 'should not']},
    {'I ___ get up early everyday.': ['have to', 'has to', 'should not', 'must not']},
    {'My sister ___ tidy up her room.': ['has to', 'have to', 'must not', 'should not']},
    {'Jane ___ do her homework.': ['has to', 'have to', 'must not', 'should']},
    {'I ___ take my car to the garage to get it fix.': ['have to', 'has to', 'must', 'should not']},
    {'You ___ attend the meeting if you are sick.': ['do not have to', 'have to', 'has to', 'must']},
    {'We ___ study for our next grammar test.': ['have to', 'has to', 'does not have to', 'should not']},
    {'Your sister ___ help to your mother.': ['has to', 'have to', 'must not', 'should not']},
]


for w in english_excercices_first_test:
    for k,v in w.items():
        answers_eng_keys[k] = v[0]

for w in english_excercices_second_test:
    for k, v in w.items():
        answers_second_test[k] = v[0]

for w in english_excercices_third_test:
    for k, v in w.items():
        answers_third_test[k] = v[0]
